### ISSUE TITLE
private_class_method def XXX is not backward compatible with ruby 2.0.0

### ISSUE THREAD

**Issue by brxue** [Eric-Guo/wechat#152]
Coding style like below can only be used for ruby 2.1+ versions,

``` ruby
     **private_class_method def self.loading_config!**
      config ||= config_from_file || config_from_environment

      if defined?(::Rails)
        config[:access_token] ||= Rails.root.join('tmp/access_token').to_s
        config[:jsapi_ticket] ||= Rails.root.join('tmp/jsapi_ticket').to_s
      end
      config[:timeout] ||= 20
      config[:have_session_class] = class_exists?('WechatSession')
      config.symbolize_keys!
      @config = OpenStruct.new(config)
    end
```

but below code works for lower versions,

``` ruby
private_class_method :loading_config!
def self.loading_config!
...
end
```

The following error will be reporte for the current implementation of **private_class_method def self.loading_config!**,

``` ruby
  Message from application: There was an error while trying to load the gem 'wechat'.
Gem Load Error is: nil is not a symbol
Backtrace for gem load error is:
/home/brxue/.gem/ruby/gems/wechat-0.7.20/lib/wechat/api_loader.rb:30:in `private_class_method'
/home/brxue/.gem/ruby/gems/wechat-0.7.20/lib/wechat/api_loader.rb:30:in `<module:ApiLoader>'
/home/brxue/.gem/ruby/gems/wechat-0.7.20/lib/wechat/api_loader.rb:2:in `<module:Wechat>'
/home/brxue/.gem/ruby/gems/wechat-0.7.20/lib/wechat/api_loader.rb:1:in `<top (required)>'
/home/brxue/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/home/brxue/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/home/brxue/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/brxue/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/home/brxue/.gem/ruby/gems/wechat-0.7.20/lib/wechat.rb:1:in `<top (required)>'
/home/brxue/.gem/ruby/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
/home/brxue/.gem/ruby/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
/home/brxue/.gem/ruby/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
/home/brxue/.gem/ruby/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
/home/brxue/.gem/ruby/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
/home/brxue/.gem/ruby/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
/home/brxue/.gem/ruby/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
/mnt/xvdb1/newair/config/application.rb:7:in `<top (required)>'
/mnt/xvdb1/newair/config/environment.rb:2:in `require'
/mnt/xvdb1/newair/config/environment.rb:2:in `<top (required)>'
config.ru:3:in `require'
config.ru:3:in `block in <main>'
/home/brxue/.gem/ruby/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
/home/brxue/.gem/ruby/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
config.ru:1:in `new'
config.ru:1:in `<main>'
/home/brxue/.gem/ruby/gems/passenger-5.0.28/src/helper-scripts/rack-preloader.rb:110:in `eval'
/home/brxue/.gem/ruby/gems/passenger-5.0.28/src/helper-scripts/rack-preloader.rb:110:in `preload_app'
/home/brxue/.gem/ruby/gems/passenger-5.0.28/src/helper-scripts/rack-preloader.rb:156:in `<module:App>'
/home/brxue/.gem/ruby/gems/passenger-5.0.28/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
/home/brxue/.gem/ruby/gems/passenger-5.0.28/src/helper-scripts/rack-preloader.rb:29:in `<main>'
Bundler Error Backtrace:
 (Bundler::GemRequireError)
  /home/brxue/.gem/ruby/gems/bundler-1.12.5/lib/bundler/runtime.rb:89:in `rescue in block (2 levels) in require'
```

Is it OK for you to make it back-compatible?

Thanks,
Brian

**Comment by Eric-Guo** [comment]
Can you make PR directly? I will accept 😃

**Comment by Eric-Guo** [comment]
Close as ruby just release 2.4 and official supported ruby version is now 2.2+
