### ISSUE TITLE
素材上传接口41005，找不到媒体文件错误

### ISSUE THREAD

**Issue by cestivan** [Eric-Guo/wechat#211]
在`rails c`中调用媒体上传接口报了`Wechat::ResponseError: media data missing hint: [bJoS6a00721492](41005)`的错误。

```ruby
irb(main):066:0> begin
irb(main):067:1* Wechat.api.media_create "image", "public/apple-touch-icon.png"
irb(main):068:1> rescue => e
irb(main):069:1> puts e.backtrace
irb(main):070:1> end
/usr/local/bundle/gems/wechat-0.8.12/lib/wechat/http_client.rb:63:in `block in request'
/usr/local/bundle/gems/wechat-0.8.12/lib/wechat/http_client.rb:83:in `parse_response'
/usr/local/bundle/gems/wechat-0.8.12/lib/wechat/http_client.rb:50:in `request'
/usr/local/bundle/gems/wechat-0.8.12/lib/wechat/http_client.rb:30:in `post_file'
/usr/local/bundle/gems/wechat-0.8.12/lib/wechat/api_base.rb:51:in `block in post_file'
/usr/local/bundle/gems/wechat-0.8.12/lib/wechat/api_base.rb:57:in `with_access_token'
/usr/local/bundle/gems/wechat-0.8.12/lib/wechat/api_base.rb:50:in `post_file'
/usr/local/bundle/gems/wechat-0.8.12/lib/wechat/api_base.rb:24:in `media_create'
```

也尝试了在命令行（Rails项目根目录下）执行同样的命令：
`wechat media_create image public/apple-touch-icon.png`
```ruby
Using rails project config/wechat.yml development setting...
/usr/local/bundle/gems/wechat-0.8.12/lib/wechat/http_client.rb:63:in `block in request': media data missing hint: [bJoS6a00721492](41005) (Wechat::ResponseError)
	from /usr/local/bundle/gems/wechat-0.8.12/lib/wechat/http_client.rb:83:in `parse_response'
	from /usr/local/bundle/gems/wechat-0.8.12/lib/wechat/http_client.rb:50:in `request'
	from /usr/local/bundle/gems/wechat-0.8.12/lib/wechat/http_client.rb:30:in `post_file'
	from /usr/local/bundle/gems/wechat-0.8.12/lib/wechat/api_base.rb:51:in `block in post_file'
	from /usr/local/bundle/gems/wechat-0.8.12/lib/wechat/api_base.rb:57:in `with_access_token'
	from /usr/local/bundle/gems/wechat-0.8.12/lib/wechat/api_base.rb:50:in `post_file'
	from /usr/local/bundle/gems/wechat-0.8.12/lib/wechat/api_base.rb:24:in `media_create'
	from /usr/local/bundle/gems/wechat-0.8.12/bin/wechat:350:in `media_create'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
```

> 这里用到的图片素材是Rails项目中默认图片，没有经过特殊处理。

**Comment by cestivan** [comment]
抱歉，经测试发现确实是图片问题，Rails项目中这个图片无法打开，换了另外正常的文件上传就可以了。

可以关闭~
