### ISSUE TITLE
升级了版本后，授权出现错误

### ISSUE THREAD

**Issue by 85636682** [Eric-Guo/wechat#240]
具体报错：
```
NoMethodError (undefined method `inject' for nil:NilClass):
omniauth-oauth2 (1.0.2) lib/omniauth/strategies/oauth2.rb:79:in `deep_symbolize'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] omniauth-wechat-oauth2 (0.1.0) lib/omniauth/strategies/wechat.rb:64:in `build_access_token'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] omniauth-oauth2 (1.0.2) lib/omniauth/strategies/oauth2.rb:62:in `callback_phase'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] omniauth (1.8.1) lib/omniauth/strategy.rb:236:in `callback_call'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] omniauth (1.8.1) lib/omniauth/strategy.rb:188:in `call!'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] omniauth (1.8.1) lib/omniauth/strategy.rb:168:in `call'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] omniauth (1.8.1) lib/omniauth/builder.rb:63:in `call'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] rack (2.0.5) lib/rack/tempfile_reaper.rb:15:in `call'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] rack (2.0.5) lib/rack/etag.rb:25:in `call'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] rack (2.0.5) lib/rack/conditional_get.rb:25:in `call'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] rack (2.0.5) lib/rack/head.rb:12:in `call'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] actionpack (5.2.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] actionpack (5.2.1) lib/action_dispatch/middleware/cookies.rb:670:in `call'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] activesupport (5.2.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] actionpack (5.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] actionpack (5.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] railties (5.2.1) lib/rails/rack/logger.rb:38:in `call_app'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] railties (5.2.1) lib/rails/rack/logger.rb:26:in `block in call'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] activesupport (5.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `tagged'
[dcb98b33-497d-4548-b06c-7ec183e6cef5] railties (5.2.1) lib/rails/rack/logger.rb:26:in `call'
```

**Comment by Eric-Guo** [comment]
从那个版本到那个版本？最近一个小版本升级其实啥都没改。。

**Comment by 85636682** [comment]
是依赖的gem版本问题引起的错误
