### ISSUE TITLE
Adding QR code interface for wechat

### ISSUE THREAD

**Issue by skinnyworm** [Eric-Guo/wechat#4]
As requested, we should add Wechat QR code support.

**Comment by flypiggy** [comment]
Any more progress?

**Comment by skinnyworm** [comment]
https://github.com/skinnyworm/wechat-rails/issues/33

**Comment by Eric-Guo** [comment]
[QR Code](http://mp.weixin.qq.com/wiki/18/28fc21e7ed87bec960651f0ce873ef8a.html) interface is means #35 ? @mxyzm
Any one interesting to implement and give a PR to me? I'm not using that feature...

**Comment by Eric-Guo** [comment]
Code finish, QR code download still have some problem.

**Comment by feitian124** [comment]
good job, i will look into it today later.

**Comment by feitian124** [comment]
经测试, 测试号和正式号均报 404 错误. 可能要去论坛问问是不是api有问题.
```sh
✔ ~/work/wechat [master L|✔] 
11:47 $ wechat qrcode_create_scene 1
{"ticket"=>"gQG98DoAAAAAAAAAASxodHRwOi8vd2VpeGluLnFxLmNvbS9xLzRFaVV6Z1BsQlNkOEZhdEI0V1lhAAIEQc8AVgMEgDoJAA==", "expire_seconds"=>604800, "url"=>"http://weixin.qq.com/q/4EiUzgPlBSd8FatB4WYa"}
✔ ~/work/wechat [master L|✔] 
11:47 $ wechat qrcode_download gQG98DoAAAAAAAAAASxodHRwOi8vd2VpeGluLnFxLmNvbS9xLzRFaVV6Z1BsQlNkOEZhdEI0V1lhAAIEQc8AVgMEgDoJAA== test.jpg
/home/ming/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!': 404 Resource Not Found (RestClient::ResourceNotFound)
	from /home/ming/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
	from /home/ming/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
	from /home/ming/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:853:in `start'
	from /home/ming/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
	from /home/ming/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
	from /home/ming/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
	from /home/ming/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient.rb:65:in `get'
	from /home/ming/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/wechat-0.4.2/lib/wechat/client.rb:15:in `block in get'
	from /home/ming/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/wechat-0.4.2/lib/wechat/client.rb:36:in `request'
	from /home/ming/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/wechat-0.4.2/lib/wechat/client.rb:13:in `get'
	from /home/ming/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/wechat-0.4.2/lib/wechat/api_base.rb:14:in `qrcode'
	from /home/ming/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/wechat-0.4.2/bin/wechat:73:in `qrcode_download'
	from /home/ming/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/ming/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/ming/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/ming/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/ming/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/wechat-0.4.2/bin/wechat:348:in `<top (required)>'
	from /home/ming/.rbenv/versions/2.2.2/bin/wechat:23:in `load'
	from /home/ming/.rbenv/versions/2.2.2/bin/wechat:23:in `<main>'
✘-1 ~/work/wechat [master L|✔] 
11:49 $ 

```

**Comment by Eric-Guo** [comment]
而且直接返回的也是404，好奇怪。。。
`http://weixin.qq.com/q/4EiUzgPlBSd8FatB4WYa`

**Comment by Eric-Guo** [comment]
在 #69 中终于 @huangxiangdan 解决了这个bug。 :+1:
