### ISSUE TITLE
wrong number of arguments (2 for 1) for subscribe event

### ISSUE THREAD

**Issue by feitian124** [Eric-Guo/wechat#47]
```ruby
 ArgumentError:
       wrong number of arguments (2 for 1)
     # ./app/controllers/wechats_controller.rb:26:in `block in <class:WechatsController>'
     # /home/ming/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/wechat-e75d5cd12414/lib/wechat/responder.rb:141:in `block in run_responder'
     # /home/ming/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/wechat-e75d5cd12414/lib/wechat/responder.rb:53:in `responder_for'
     # /home/ming/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/wechat-e75d5cd12414/lib/wechat/responder.rb:132:in `run_responder'
     # /home/ming/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/wechat-e75d5cd12414/lib/wechat/responder.rb:94:in `create'
```

```ruby
  # 用户关注
  on :event, with: "subscribe" do |request|
      request.reply.text "欢迎关注!"
  end
```
以上的代码不工作了, 好像和 cd0b8744f9ed483ed3764877de94bf0fcfe1babc 有关.

```ruby
define_singleton_method :process, responder[:proc]
send(:process, *args.unshift(request))
```
看上去似乎是 define_singleton_method 动态定义的方法只需要一个参数, 但 unshift 出来了2个. 我继续跟一下.

**Comment by Eric-Guo** [comment]
嗯，虽然可以这样写，不过也算一个bug吧。。

```
  # 当用户加关注
  on :event, with: 'subscribe' do |request, key|
    request.reply.text "#{request[:FromUserName]} #{key} now"
  end
```

**Comment by feitian124** [comment]
```ruby
undefined local variable or method `wechat' for #<WechatsController:0x007fc7c73e88e8>
```
as per #15, 现在上下文不是 class 了吗? wechat 取不到了, 但是 on 方法里面如果还需要呢

**Comment by Eric-Guo** [comment]
我改了一下，现在好了，你看看？

**Comment by feitian124** [comment]
谢谢, wrong number of arguments (2 for 1) 这个是可以了.
那现在
```ruby
 # 当用户加关注
  on :event, with: 'subscribe' do |request|
    user_json = wechat.user request[:FromUserName]
    request.reply.text "#{request[:FromUserName]} #{key} now"
  end
```
那现在 wechat 在 on 里面里面怎么取呢? 貌似取不到了?

**Comment by Eric-Guo** [comment]
现在可以了。 :smiley:

**Comment by Eric-Guo** [comment]
@feitian124 如果没啥问题，明天发布0.4.2！

**Comment by feitian124** [comment]
可以了,谢谢, 原有接口保留了.

**Comment by Eric-Guo** [comment]
:+1: 已经发布0.4.2
