### ISSUE TITLE
skip_verify_ssl: false的设置对命令行无效

### ISSUE THREAD

**Issue by goofansu** [Eric-Guo/wechat#50]
命令行里执行wechat就报SSL的错误，我就把`skip_verify_ssl: false`加到`~/.wechat.yml`，但是无效

PS：感谢这个库，替换掉了我自己的逻辑，删了大片代码，很爽

**Comment by Eric-Guo** [comment]
我没有复现出这个错，你的wechat版本是0.4.2么？还有需要检查是否wechat读取的rails的配置，如果在某个rails项目根目录下运行，wechat会读取`RAILS_ROOT/config/wechat.yml`，而不是`~/.wechat.yml`

**Comment by goofansu** [comment]
``` shell
~ ❯❯❯ cat ~/.wechat.yml                                                       ⏎
appid: "wx0aad0d07acc91b94"
secret: "09b4223ab81f54154796b805ea395d48"
access_token: "/var/tmp/wechat_access_token"
skip_verify_ssl: false
~ ❯❯❯ wechat users
/opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/requ
est.rb:445:in `rescue in transmit': SSL_connect returned=1 errno=0 state=unknown
 state: certificate verify failed (RestClient::SSLCertificateNotVerified)
        from /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/re
stclient/request.rb:350:in `transmit'
        from /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/re
stclient/request.rb:176:in `execute'
        from /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/re
stclient/request.rb:41:in `execute'
        from /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/re
stclient.rb:65:in `get'
        from /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/wechat-0.4.2/lib/wechat/
client.rb:15:in `block in get'
        from /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/wechat-0.4.2/lib/wechat/
client.rb:36:in `request'
        from /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/wechat-0.4.2/lib/wechat/
client.rb:13:in `get'
        from /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/wechat-0.4.2/lib/wechat/
access_token.rb:25:in `refresh'
        from /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/wechat-0.4.2/lib/wechat/
access_token.rb:19:in `rescue in token'
        from /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/wechat-0.4.2/lib/wechat/
access_token.rb:13:in `token'
```

**Comment by Eric-Guo** [comment]
`skip_verify_ssl: false`要设置成true，哇哈哈！

**Comment by goofansu** [comment]
@Eric-Guo 啊，不好意思，一直陷在之前的思维里

rails里没报错是因为我还没用API，我稍后看看，应该没问题
